Repository weareinreach/TransMascFutures, pull requests merged in 2023-06, with the labels that each got.

#35 feat: about page (GC-13)
  src/pageStories/AboutPage.stories.tsx
  src/pages/about.tsx
Labels: automerge, new-feature

#29 feat: Admin edit story attributes (GC-21)
  prisma/seed.ts
  src/pageStories/MainPage.stories.tsx
  src/pages/category/[category].tsx
  src/pages/index.tsx
  src/server/api/routers/admin.ts
  src/server/api/routers/stories.ts
Labels: automerge, new-feature

#33 feat: Admin manage supporting partners links (GC-23)
  src/server/api/routers/admin.ts
  src/server/api/routers/stories.ts
Labels: automerge, new-feature

#57 fix: update favicon
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
  src/pages/_app.tsx
Labels: bugfix

#66 release: 2023-06-12
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/pr-labels.yml
  .gitignore
  package.json
  pnpm-lock.yaml
  prisma/client.ts
  prisma/data-migrations/!YYYY-MM-DD_job-template.ts
  prisma/data-migrations/2023-06-12_add-stories/!prepare.ts
  prisma/data-migrations/2023-06-12_add-stories/in.json
  prisma/data-migrations/2023-06-12_add-stories/index.ts
  prisma/data-migrations/2023-06-12_add-stories/sTc.json
  prisma/data-migrations/2023-06-12_add-stories/sTp.json
  prisma/data-migrations/2023-06-12_add-stories/stories.json
  prisma/data-migrations/index.ts
  prisma/dataMigrationRunner.ts
  prisma/jobPreRun.ts
  prisma/migration-logs/.gitkeep
  prisma/migrations/20230612144441_add_migration_table/migration.sql
  prisma/migrations/20230612155611_cascade_delete/migration.sql
  prisma/schema.prisma
  tsconfig.json
  turbo.json
Labels: automerge, maintenance

#77 release: 2023-06-20
  .github/workflows/chromatic.yml
  .github/workflows/codeql.yml
  .github/workflows/pr-labels.yml
  package.json
  pnpm-lock.yaml
  prisma/data-migrations/2023-06-20_add-stories/!prepare.ts
  prisma/data-migrations/2023-06-20_add-stories/in.json
  prisma/data-migrations/2023-06-20_add-stories/index.ts
  prisma/data-migrations/2023-06-20_add-stories/sTc.json
  prisma/data-migrations/2023-06-20_add-stories/sTp.json
  prisma/data-migrations/2023-06-20_add-stories/stories.json
  prisma/data-migrations/index.ts
  src/pages/category/[tag]/[[...storyId]].tsx
  src/pages/story/[id].tsx
Labels: automerge

#82 feat: add story, create sitemap
  .github/autoapprove-config.yaml
  .github/workflows/chromatic.yml
  .github/workflows/lint.yml
  .github/workflows/pr-labels.yml
  .npmrc
  next-sitemap.config.js
  package.json
  pnpm-lock.yaml
  prisma/data-migrations/2023-06-27_add-story.ts
  prisma/data-migrations/index.ts
  prisma/migrations/20230627163328_add_tag_field/migration.sql
  prisma/schema.prisma
  src/server/api/routers/stories.ts
Labels: automerge, maintenance, new-feature
